name: Automatically close issues with a comment

on:
    issues:
        types: [opened]

jobs:
    close_issue:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Add a comment and close
              env:
                GH_TOKEN: ${{ github.token }}
              run: |
                # Get issue number
                issue_number=${{ github.event.issue.number }}

                # Add comment
                gh issue comment --body "This issue is automatically closed. Please refer to [documentation link](your_documentation_link) for further details." $issue_number

                # Close issue
                gh issue close $issue_number
