name: Automatically close issues with a comment

on:
    issues:
        types: [opened]

jobs:
    close_issue:
        permissions:
            issues: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Add a comment and close
              env:
                GH_TOKEN: ${{ github.token }}
              run: |
                # Get issue number
                issue_number=${{ github.event.issue.number }}
                issue_reporter=${{ github.event.issue.user }}

                # Add comment
                gh issue comment $issue_number --body <<EOF
                Hi $issue_reporter!

                The primary -- and the correct -- way to report an issue to us is via the customer support channel. Send us an email at support@blueshift.com from your work email with all the necessary details that contain step by step instructions on how to reproduce the issue.

                In addition, include the following details based on the nature of the issue.

                - Crash Log (in case of app crash)
                - Screenshots/Screen Recordings
                - Device details (Make, OS version etc)
                - Blueshift Android/iOS SDK version being used
                - Campaign Name/Link (if available)
                - Template Name/Link (if available)

                Any extra details that you think would help in repro the issue
                EOF

                # Close issue
                gh issue close $issue_number
